import Foundation

/// GPT-2's byte-level BPE, which is what Chatterbox Nano reads text with.
///
/// Nano inherited the stock GPT-2 tokenizer plus nineteen bracketed style tags
/// (`[laugh]`, `[whispering]` and so on) bolted on above the 50257 base
/// vocabulary. Nothing is prepended or appended: unlike most models there is no
/// BOS or EOS around the text, because T3 wraps the sequence itself.
///
/// "Byte-level" is the part worth understanding. Text is encoded to UTF-8 and
/// each byte is mapped to a printable character before any merging happens, so
/// there is no unknown token and no normalisation — every byte sequence has
/// exactly one encoding. That also means this must agree with the Python
/// tokenizer byte for byte, which `BPETokenizerTests` checks against fixtures
/// generated by it.
public struct BPETokenizer: Sendable {
    private let encoder: [String: Int]
    private let ranks: [Pair: Int]
    private let added: [(String, Int)]
    private let byteToUnicode: [UInt8: Character]

    struct Pair: Hashable, Sendable {
        let left: String
        let right: String
    }

    public enum LoadError: Error, LocalizedError {
        case missing(String)
        case malformed(String)

        public var errorDescription: String? {
            switch self {
            case .missing(let what): "Tokenizer file missing: \(what)"
            case .malformed(let what): "Tokenizer file malformed: \(what)"
            }
        }
    }

    /// Load from the three files the Nano checkpoint ships: `vocab.json`,
    /// `merges.txt` and `added_tokens.json`.
    public init(directory: URL) throws {
        func read(_ name: String) throws -> Data {
            let url = directory.appendingPathComponent(name)
            guard let data = try? Data(contentsOf: url) else { throw LoadError.missing(name) }
            return data
        }

        guard let vocab = try JSONSerialization.jsonObject(with: read("vocab.json")) as? [String: Int] else {
            throw LoadError.malformed("vocab.json")
        }
        guard let merges = String(data: try read("merges.txt"), encoding: .utf8) else {
            throw LoadError.malformed("merges.txt")
        }
        let extra = (try? JSONSerialization.jsonObject(with: read("added_tokens.json"))) as? [String: Int]

        var ranks: [Pair: Int] = [:]
        var rank = 0
        // Split on any newline, so a merges.txt saved with CRLF endings does
        // not leave a `\r` on every right-hand symbol — that made *no* merge
        // ever match, and every byte became its own token, silently.
        for line in merges.split(whereSeparator: \.isNewline) {
            // The first line is normally a `#version:` comment, but only skip
            // what actually is one — unconditionally dropping the first line
            // would discard the highest-priority merge from a file without it.
            // (Only the literal header: real merges can begin with `#`.)
            if line.hasPrefix("#version") { continue }
            let parts = line.split(separator: " ")
            guard parts.count == 2 else { continue }
            ranks[Pair(left: String(parts[0]), right: String(parts[1]))] = rank
            rank += 1
        }

        self.encoder = vocab
        self.ranks = ranks
        // Longest first, so `[clear throat]` is not matched as `[c`...
        self.added = (extra ?? [:]).sorted { $0.key.count > $1.key.count }.map { ($0.key, $0.value) }
        self.byteToUnicode = Self.byteEncoder()

        // A tokenizer that loads but cannot tokenize is worse than one that
        // fails here: `encodeWord` drops symbols the vocabulary lacks, so a
        // skewed vocab/merges pair deletes words from the audio with no
        // diagnostic anywhere. Every byte symbol and every merge product must
        // be encodable, and there must be merges at all.
        guard !ranks.isEmpty else { throw LoadError.malformed("merges.txt (no merges)") }
        for character in byteToUnicode.values where vocab[String(character)] == nil {
            throw LoadError.malformed("vocab.json (missing byte symbol \(character))")
        }
        for pair in ranks.keys where vocab[pair.left + pair.right] == nil {
            throw LoadError.malformed("merges.txt (merge \(pair.left)+\(pair.right) not in vocab.json)")
        }
    }

    public var count: Int { encoder.count + added.count }

    /// GPT-2's byte alphabet: printable ASCII and Latin-1 keep their own code
    /// point, and everything else is lifted into the 256..<512 range so that no
    /// byte maps to a space or a control character.
    static func byteEncoder() -> [UInt8: Character] {
        var codes: [Int] = Array(33...126) + Array(161...172) + Array(174...255)
        var mapped = codes
        var next = 0
        for byte in 0..<256 where !codes.contains(byte) {
            codes.append(byte)
            mapped.append(256 + next)
            next += 1
        }
        var out: [UInt8: Character] = [:]
        for (byte, code) in zip(codes, mapped) {
            out[UInt8(byte)] = Character(UnicodeScalar(code)!)
        }
        return out
    }

    /// GPT-2's pre-tokenizer: contractions, then runs of letters, digits and
    /// punctuation, each keeping the space in front of it.
    static let pattern = "'s|'t|'re|'ve|'m|'ll|'d| ?\\p{L}+| ?\\p{N}+| ?[^\\s\\p{L}\\p{N}]+|\\s+(?!\\S)|\\s+"
    private static let regex = try! NSRegularExpression(pattern: pattern)

    func words(in text: String) -> [String] {
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        return Self.regex.matches(in: text, range: range).compactMap {
            Range($0.range, in: text).map { String(text[$0]) }
        }
    }

    /// Merge the highest-ranked adjacent pair until none is left.
    func merge(_ symbols: [String]) -> [String] {
        var symbols = symbols
        while symbols.count > 1 {
            var best: (rank: Int, index: Int)?
            for index in 0..<(symbols.count - 1) {
                guard let rank = ranks[Pair(left: symbols[index], right: symbols[index + 1])] else { continue }
                if best == nil || rank < best!.rank { best = (rank, index) }
            }
            guard let found = best else { break }
            symbols.replaceSubrange(
                found.index...(found.index + 1),
                with: [symbols[found.index] + symbols[found.index + 1]]
            )
        }
        return symbols
    }

    private func encodeWord(_ word: String) -> [Int] {
        let symbols = Array(word.utf8).compactMap { byteToUnicode[$0] }.map(String.init)
        return merge(symbols).compactMap { encoder[$0] }
    }

    public func encode(_ text: String) -> [Int] {
        // Style tags are literal strings that must not be split, so they are
        // carved out before the byte-level pass ever sees them.
        for (literal, id) in added {
            guard let found = text.range(of: literal) else { continue }
            return encode(String(text[text.startIndex..<found.lowerBound]))
                + [id]
                + encode(String(text[found.upperBound...]))
        }
        return words(in: text).flatMap(encodeWord)
    }
}
