import Foundation

/// The grapheme BPE that Chatterbox Multilingual reads text with.
///
/// Nothing like Nano's. Where that one is GPT-2's byte-level BPE over 50276
/// English byte pairs, this is a 2454-entry vocabulary of *letters* — plus 265
/// merges, a bracketed tag per language, and `[SPACE]` standing in for the
/// space character. A sentence comes out roughly one token per letter, which is
/// why the same chunk of text is several times more tokens here than on the
/// phone.
///
/// The pipeline is HuggingFace's, reproduced stage for stage:
///
/// 1. lowercase, then NFKD — so `café` becomes `cafe` + a combining accent, and
///    the accent is a token of its own
/// 2. prepend the language tag: `[nl]`, `[de]`, …
/// 3. every space becomes the added token `[SPACE]`
/// 4. split on added tokens, longest match first
/// 5. pre-tokenize what is left with `\w+|[^\w\s]+`, which is what
///    `tokenizers`' `Whitespace` does — letters and punctuation part company
/// 6. BPE each piece, unknown characters becoming `[UNK]` individually
///
/// `MTLTokenizerTests` holds it to a fixture generated by the Python original,
/// because "reproduced stage for stage" is a claim about output, not intent.
///
/// ## The five languages this refuses
///
/// Chinese, Japanese, Hebrew, Korean and Russian each route through a separate
/// Python package before tokenising — Cangjie decomposition, kakasi, Dicta
/// diacritics, jamo normalisation, stress marking. Those are not ported, and a
/// port that skipped them would not fail: it would mispronounce confidently,
/// which is the one failure mode this codebase keeps refusing. So they are
/// declined by name, and the app says the language is unsupported rather than
/// reading it wrongly.
public struct MTLTokenizer: Sendable {
    /// Languages whose text needs a normaliser that is not ported.
    public static let needsNormalizer: Set<String> = ["zh", "ja", "he", "ko", "ru"]

    private let vocabulary: [String: Int32]
    private let ranks: [Pair: Int]
    /// Added tokens, longest first: `[SPACE]` must not be found inside
    /// `[SPACEX]` if such a thing were ever added.
    private let added: [String]
    private let unknown: Int32
    private let space: Int32
    private let wordBoundary: NSRegularExpression

    struct Pair: Hashable, Sendable {
        let left: String
        let right: String
    }

    public enum LoadError: Error, LocalizedError {
        case missing(String)
        case malformed(String)

        public var errorDescription: String? {
            switch self {
            case .missing(let what):
                "Tokenizer file missing: \(what). Run: bun run mac:install"
            case .malformed(let what): "Tokenizer file malformed: \(what)"
            }
        }
    }

    public static let filename = "grapheme_mtl_merged_expanded_v1.json"

    /// Load from the single JSON the multilingual checkpoint ships.
    public init(directory: URL) throws {
        let url = directory.appendingPathComponent(Self.filename)
        guard let data = try? Data(contentsOf: url) else {
            throw LoadError.missing(Self.filename)
        }
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let model = root["model"] as? [String: Any],
              let vocab = model["vocab"] as? [String: Int],
              let merges = model["merges"] as? [Any]
        else { throw LoadError.malformed(Self.filename) }

        vocabulary = vocab.mapValues(Int32.init)
        guard let unknown = vocabulary["[UNK]"], let space = vocabulary["[SPACE]"] else {
            throw LoadError.malformed("\(Self.filename): no [UNK] or [SPACE]")
        }
        self.unknown = unknown
        self.space = space

        // Merges are "left right" in rank order. Newer `tokenizers` writes them
        // as two-element arrays instead, so both shapes are read — the file is
        // the checkpoint's, and its format is not ours to pin.
        var ranks: [Pair: Int] = [:]
        for (rank, entry) in merges.enumerated() {
            let parts: [String]
            if let line = entry as? String {
                parts = line.split(separator: " ").map(String.init)
            } else if let pair = entry as? [String] {
                parts = pair
            } else {
                throw LoadError.malformed("\(Self.filename): merge \(rank)")
            }
            guard parts.count == 2 else { throw LoadError.malformed("\(Self.filename): merge \(rank)") }
            ranks[Pair(left: parts[0], right: parts[1])] = rank
        }
        self.ranks = ranks

        let declared = (root["added_tokens"] as? [[String: Any]])?
            .compactMap { $0["content"] as? String } ?? []
        // Every bracketed entry in the vocabulary, not only the declared ones:
        // the language tags live in both lists in this checkpoint, and a tag
        // that were only in the vocabulary would otherwise be BPE'd into
        // `[`, `n`, `l`, `]`.
        let bracketed = vocabulary.keys.filter { $0.hasPrefix("[") && $0.hasSuffix("]") }
        added = Array(Set(declared + bracketed)).sorted {
            $0.count > $1.count || ($0.count == $1.count && $0 < $1)
        }

        // `tokenizers`' Whitespace pre-tokenizer, verbatim.
        wordBoundary = try NSRegularExpression(pattern: #"\w+|[^\w\s]+"#)
    }

    /// Whether this tokenizer will read the given language honestly.
    public func canRead(_ language: String) -> Bool {
        let code = language.lowercased()
        return vocabulary["[\(code)]"] != nil && !Self.needsNormalizer.contains(code)
    }

    /// Every language the vocabulary has a tag for and this port can normalise.
    public var languages: [String] {
        vocabulary.keys.compactMap { key in
            guard key.hasPrefix("["), key.hasSuffix("]") else { return nil }
            let code = String(key.dropFirst().dropLast())
            guard code.count == 2, code.allSatisfy(\.isLowercase),
                  !Self.needsNormalizer.contains(code)
            else { return nil }
            return code
        }
        .sorted()
    }

    /// Text to token ids, language tag included.
    public func encode(_ text: String, language: String) -> [Int32] {
        let prepared = "[\(language.lowercased())]"
            + text.lowercased().decomposedStringWithCompatibilityMapping
        var out: [Int32] = []
        for piece in split(prepared) {
            switch piece {
            case .token(let id):
                out.append(id)
            case .text(let run):
                for word in words(in: run) { out.append(contentsOf: bpe(word)) }
            }
        }
        return out
    }

    // MARK: - The stages

    private enum Piece {
        case token(Int32)
        case text(String)
    }

    /// Cut the string on added tokens, and on spaces — which are `[SPACE]`.
    ///
    /// Done in one pass rather than by string replacement first: substituting
    /// `[SPACE]` into the text would let a literal "[SPACE]" a book happened to
    /// contain become a space, and scanning is no harder.
    private func split(_ text: String) -> [Piece] {
        var out: [Piece] = []
        var pending = ""
        var index = text.startIndex

        func flush() {
            if !pending.isEmpty {
                out.append(.text(pending))
                pending = ""
            }
        }

        outer: while index < text.endIndex {
            if text[index] == " " {
                flush()
                out.append(.token(space))
                index = text.index(after: index)
                continue
            }
            if text[index] == "[" {
                for candidate in added where text[index...].hasPrefix(candidate) {
                    flush()
                    out.append(.token(vocabulary[candidate] ?? unknown))
                    index = text.index(index, offsetBy: candidate.count)
                    continue outer
                }
            }
            pending.append(text[index])
            index = text.index(after: index)
        }
        flush()
        return out
    }

    private func words(in run: String) -> [String] {
        let text = run as NSString
        return wordBoundary
            .matches(in: run, range: NSRange(location: 0, length: text.length))
            .map { text.substring(with: $0.range) }
    }

    /// One word, merged as far as the ranks allow.
    ///
    /// Split by Unicode *scalar* rather than by `Character`, and that is the
    /// whole difficulty: a Swift `Character` is a grapheme cluster, so `o`
    /// followed by a combining diaeresis is one Character — and this
    /// vocabulary happens to contain the precomposed `ö` as well, so the
    /// mistake does not throw, it silently produces a different token than the
    /// Python original, which iterates code points. NFKD decomposed the accent
    /// on purpose; recomposing it here would undo that.
    private func bpe(_ word: String) -> [Int32] {
        var symbols = word.unicodeScalars.map(String.init)
        guard symbols.count > 1 else { return symbols.map { vocabulary[$0] ?? unknown } }

        while symbols.count > 1 {
            var best: (rank: Int, index: Int)?
            for index in 0..<(symbols.count - 1) {
                guard let rank = ranks[Pair(left: symbols[index], right: symbols[index + 1])]
                else { continue }
                if best == nil || rank < best!.rank { best = (rank, index) }
            }
            guard let winner = best else { break }
            symbols.replaceSubrange(
                winner.index...(winner.index + 1),
                with: [symbols[winner.index] + symbols[winner.index + 1]]
            )
        }
        // `fuse_unk` is false in this checkpoint: an unknown symbol is its own
        // token rather than being merged with the ones beside it.
        return symbols.map { vocabulary[$0] ?? unknown }
    }
}
